---
title: "Untitled"
output: html_document
date: "2022-12-06"
---

```{r install packages}
setwd("C:/Users/torriw/Desktop/leah")
install.packages("dplyr")
install.packages("devtools")
BiocManager::install("biomaRt")
library(biomaRt)
```

```{r using h19 to build }
snp_txt<-read.delim("dasiigcaperc_summary_stats.txt")
#snp_txt_4<-snp_txt[snp_txt$neg_log_pvalue > 3.99,]
snp_txt_3<-snp_txt[snp_txt$neg_log_pvalue > 3,]
#snp_list_full<-snp_txt_4$rsid
snp_list_3<-snp_txt_3$rsid
half_list<-snp_list_3[1:5000]

add_perc<-read.delim("add_dasiigcaperc_summary_stats.txt")
add_perc_5<-add_perc[add_perc$neg_log_pvalue > 5,]
add_perc_5_list<-add_perc_5$rsid
add_perc_short<-add_perc_5_list[10000:19071]
```

```{r mart}

#Mart used to map SNPs to Ensembl Gene IDs
grch37.snp = useMart(biomart="ENSEMBL_MART_SNP", host="grch37.ensembl.org", path="/biomart/martservice",dataset="hsapiens_snp")

#Mart used to map Ensembl Gene IDs to Gene name
grch37 = useMart(biomart="ENSEMBL_MART_ENSEMBL", host="grch37.ensembl.org", path="/biomart/martservice", dataset="hsapiens_gene_ensembl")

```

```{r Mapping SNPs to Ensembl Gene IDs}
table1 <- getBM(attributes = c("refsnp_id", "ensembl_gene_stable_id"), 
                      filters = "snp_filter", 
                      values = snp_list_3 , 
                      mart = grch37.snp)

add_table1<- getBM(attributes = c("refsnp_id","ensembl_gene_stable_id"), 
                      filters = "snp_filter", 
                      values = add_perc_5_list , 
                      mart = grch37.snp)

```

```{r Mapping Ensembl Gene IDs to Gene names }
# "ensembl_gene_id", "external_gene_name","external_gene_source","variation_name","start_position","end_position","description"

# find info on specific genes (BHMT2, MTHFD1L) for value portion of code to quicker the process 

table2 <- getBM(attributes = c("ensembl_gene_id","external_gene_name"),
                 filters = "ensembl_gene_id", 
                 values =  table1$ensembl_gene_stable_id, 
                 mart = grch37)
write.csv(table2,"C:/Users/torriw/Desktop/leah/dasiirecdest_gene_list3.csv",row.names = F)

add_table2 <- getBM(attributes = c("ensembl_gene_id","external_gene_name"),
                 filters = "ensembl_gene_id", 
                 values =  add_table1$ensembl_gene_stable_id, 
                 mart = grch37)

```

```{r check for choline genes }
# Choline genes of interest
# MTHFR CHDH CEPT1 PEMT BHMT CHKA CHKAB CHPT PCYTIA PCYTIB DHFR MTHFD1 

###if there's a larger list and you don't want to check one by one###
genelist<-c("CYP2E1","ALDH1L1", "DMGDH", "MAT1A", "SLC25A26", "MMAB", "ABCB1", "GGH", "CTH", "SLC2A1", "MSRA", "MARS","BHMT2", "MTHFD1L" )
genelist %in% add_table2$external_gene_name

# output results
#  [1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE

# genecheck<-add_table2$external_gene_name == "CYP2E1"
for (i in genecheck) {
  if (i == "TRUE"){
     print(i)
  }
}

# if nothing prints then the gene is not in the list
```

```{r find snps and negative pvalues from matching genes }
# find gene id 
table2[table2$external_gene_name == "BHMT2",] # ENSG00000132840
table2[table2$external_gene_name == "MTHFD1L",] # ENSG00000120254

add_gene_list<-c("ALDH1L1","SLC25A26","CTH","CYP2E1","MMAB", "MSRA","GGH","MTHFD1L")

# find snp from gene id
table1[table1$ensembl_gene_stable_id == "ENSG00000132840",] # rs671960
table1[table1$ensembl_gene_stable_id == "ENSG00000120254",] # rs742830,rs2096066,rs3734418,rs6933598,rs9767752,rs11155761

for (i in add_gene_list){
  if (i %in% add_table2$external_gene_name){
    ids<-(add_table2[add_table2$external_gene_name==i,])
      #print(ids) #this will print out id's for the next step
      id_list<-c("ENSG00000144908","ENSG00000144741","ENSG00000261657","ENSG00000116761","ENSG00000130649","ENSG00000139428","ENSG00000175806","ENSG00000137563","ENSG00000120254")
        for (j in id_list){
          if (j %in% add_table1$ensembl_gene_stable_id){
            snps<-(add_table1[add_table1$ensembl_gene_stable_id ==j,])
            #my_snps[[j]]<-(add_table1[add_table1$ensembl_gene_stable_id ==j,])
            print.data.frame(snps)
          }
        }
      }
    }

#next time seperate for loops, things from first loop are seeping over into second loop

#find pvalues of snps
new_snps<-read.csv("C:/Users/torriw/Desktop/leah/new_snp_list.csv")
# snp_txt[snp_txt$rsid == "rs2736683",]

 snplist<- c("rs1045642","rs2235048")
#,"rs61940463","rs61940465","rs61940466","rs73414076")
#,"rs332360","rs36067519")
#,"rs12254222","rs12254225","rs12257054","rs12761234","rs12762259","rs71505853","rs41258504")
 # for (i in snplist){
 #   for (j in snp_txt$rsid){
 #     if (i %in% j){
 #       pvals<-(snp_txt[snp_txt$rsid == i,])
 #       pvals<-list(pvals)
 #       print(pvals)
 #     }
 #   }
 # }

new_snps_list<-c(new_snps$refsnp_id)
for (i in new_snps_list){
  for (j in add_perc_5$rsid){
    if (i %in% j){
      pvals<-(add_perc_5[add_perc_5$rsid == i,])
      pvals<-list(pvals)
      print.simple.list(pvals) #this prints so that each column is seperated, take this output, save as a txt file, transform in excel, and transpose on new worksheet 
    }
  }
}


```

```{r find pvalues from matching genes }
# > logp<-3.447604367911758
# > 10^-logp
# [1] 0.000356776

output<-read.csv("C:/Users/torriw/Desktop/leah/new_list_output.csv")
neg_p<-output$neg_log_pvalue
ps<-10^-neg_p
ps<-data.frame(ps)
output<-cbind(output,ps)
write.csv(output,"C:/Users/torriw/Desktop/leah/new_list_output.csv",row.names = FALSE)

```
